HAC.Web/Controllers/AnnouncementController.cs
using HAC.Domain;
using HAC.Domain.Repositories;
using PagedList;
using System;
using System.Linq;
using System.Web.Mvc;

namespace HAC.Controllers
{
    public class AnnouncementController : Controller
    {
        //
        // GET: /Announcement/


        public ActionResult Index()
        {
            var announcementRepository = new AnnouncementRepository();
            var activeAnnouncements = announcementRepository.GetActiveAnnouncements().ToList();
            return View(activeAnnouncements);
        }

        public object Archive(int? page)
        {
            var announcementRepository = new AnnouncementRepository();
            var archivedAnnouncements = announcementRepository.GetArchivedAnnouncements();
            var pageNumber = page ?? 0; // if no page was specified in the querystring, default to the first page (1)
            var onePageOfAnnouncements = archivedAnnouncements.ToPagedList(pageNumber, 10); // will only contain 25 products max because of the pageSize

            ViewBag.OnePageOfAnnouncements = onePageOfAnnouncements;
            return View("Archive");
        }

        //
        // GET: /Announcement/Details/5

        public ActionResult Details(int id)
        {
            var announcement = new Announcement();
            return View("Create", announcement);
        }

        //
        // GET: /Announcement/Create
        //[Authorize]
        //[HttpGet]
        public ActionResult Create()
        {
            return View("Create");
        }


        //[HttpGet]
        //public ActionResult Amend()
        //{
        //    var announcement = new Announcement();
        //    return PartialView("Amend", announcement);
        //}

        [HttpGet]
        public ActionResult Amend(int id)
        {
            var announcementRepository = new AnnouncementRepository();
            Announcement announcement;
            if (id > 0)
            {
                announcement = announcementRepository.GetAnnouncementById(id);
            }
            else
            {
                announcement = new Announcement()
                    {
                        ExpiryDate = System.DateTime.Today
                    };
            }

            return PartialView("Amend", announcement);
        }

        //
        // POST: /Announcement/Create
        //[Authorize]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Save(Announcement announcement)
        {
            try
            {

                var announcementRepository = new AnnouncementRepository();
           //     announcement.userName = HttpContext.User.Identity.Name;
                if (HttpContext.Session != null)
                    announcement.UserId = HttpContext.Session["UserId"] as int?;

                announcement.CreateDate = DateTime.Now.Date;
                announcement.LastModified = DateTime.Now.Date;
                announcementRepository.Save(announcement);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw (ex);
            }
        }

        //
        // GET: /Announcement/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Announcement/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Announcement/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Announcement/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

HAC.Web/Controllers/CategoryController.cs
using HAC.Domain;
using HAC.Domain.Repositories;
using HAC.Models;
using ImageResizer;
using System;
using System.Drawing;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace HAC.Controllers
{
    public class CategoryController : BaseController
    {
        //[OutputCache(Duration = 0, VaryByParam = "folder")] //carefull, don't use cache here, different responses whatever is ajax request or not!
        public ActionResult List(int iCat)
        {
            PhotoRepository rep = this.GetPhotoRepository();
            //string vPathFolder = Util.StripFirstSlashFromVirtualPath(HttpUtility.UrlDecode(folder));

            var images = rep.GetCategoryImages(iCat);
            if (images == null)
            {
                Response.StatusCode = 400;
                return Json(new { error = "Error, category not found on id: " + iCat }, JsonRequestBehavior.AllowGet);
            }


            ////check security
            //if (!pgfolder.IsUserGranted(User.Identity.Name)) {
            //        Response.StatusCode = 403;
            //        return Json(new { error = "This is a private folder. You need access to read its content." }, JsonRequestBehavior.AllowGet);                
            //}

            //string content = pgfolder.GetHtmlContentIfAny();

            System.Collections.ArrayList list = new System.Collections.ArrayList();
            foreach (var image in images)
            {
                list.Add(new
                {
                    VPath = Util.GetApplicationFullUrlWithoutLastSlash() + "/ImageView?ImageVPath=" + HttpUtility.UrlEncode(image.PIC_IMAGE),
                    UrlThumbnail = Util.GetApplicationFullUrlWithoutLastSlash() + "/ThumbnailView/120/120?ImageVPath=" + HttpUtility.UrlEncode(image.PIC_IMAGE),
                    Url = HttpContext.Request.ApplicationPath.TrimEnd('/') + "/Image/" + image.PIC_ID,
                    UrlFullImage = Util.GetApplicationFullUrlWithoutLastSlash() + "/ImageView?ImageVPath=" + HttpUtility.UrlEncode(image.PIC_IMAGE),
                    Name = image.PIC_NAME,
                });
            }

            string content = "";

            if (images.Count == 0)
            {
                return View("../PHOTOS/Index");
            }


            if (Request.IsAjaxRequest())
                return Json(new { thumbnails = list, htmlcontent = content }, JsonRequestBehavior.AllowGet);
            else
            {
                ViewBag.SelectedImage = "Image/" + images[0].PIC_ID;
                ViewBag.Categories = rep.GetCategories();
                ViewBag.SelectedCategory = Util.GetApplicationFullUrlWithoutLastSlash() + "/PHOTOS/Category/List/" + iCat;

                return View("../PHOTOS/Index");
            }

        }

        [HttpPost]
        public ActionResult Add(PIC_CATEGORIES currentCategory, HttpPostedFileBase imageFile)
        {
            // Verify that the user selected a file
            if (imageFile != null && imageFile.ContentLength > 0)
            {
                currentCategory.CAT_IMAGE = Guid.NewGuid() + Path.GetExtension(imageFile.FileName);
                var path = Path.Combine(Configuration.GetPicturesPhysicalPath, currentCategory.CAT_IMAGE);


                var settings = new ResizeSettings
                {
                    MaxWidth = 375,
                    MaxHeight = 500,
                    Format = "jpg"
                };
                Bitmap bitmap = ImageBuilder.Current.Build(imageFile, settings);
                bitmap.Save(path);
                bitmap.Dispose();
             //   currentCategory.CAT_DATED = DateTime.Now;
              //  currentCategory.CAT_GROUP = 9;
                PhotoRepository rep = this.GetPhotoRepository();
                rep.Save(currentCategory);
            }

            return RedirectToRoute("PhotosCategoryList", new { id = currentCategory.CAT_ID });
        }
    }
}

HAC.Web/Controllers/EventsController.cs
using HAC.Domain;
using HAC.Domain.Repositories;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace HAC.Controllers
{
    public class EventsController : Controller
    {
        //
        // GET: /Events/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Calendar()
        {
            return View("Calendar");
        }

        [HttpGet]
        public ActionResult Amend(int id)
        {
            var eventRepository = new EventRepository();
            Event _event;

            if (id > 0)
            {
                _event = eventRepository.GetNewsEvent(id);
            }
            else
            {
                _event = new Event();

            }

            return PartialView("Amend", _event);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Save(Event announcement)
        {
            try
            {

                //var announcementRepository = new AnnouncementRepository();
                //announcement.UserName = HttpContext.User.Identity.Name;
                //if (HttpContext.Session != null)
                //    announcement.UserId = HttpContext.Session["UserId"] as int?;

                //announcement.CreateDate = DateTime.Now.Date;
                //announcement.LastModified = DateTime.Now.Date;
                //announcementRepository.Save(announcement);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                throw (ex);
            }
        }


        public ActionResult CalendarData(double start, double end)
        {
            var fromDate = ConvertFromUnixTimestamp(start);
            var toDate = ConvertFromUnixTimestamp(end);
 
            var eventRepository = new EventRepository();
            IList<CalendarDTO> eventsList = new List<CalendarDTO>();
            foreach (var ev in eventRepository.GetEvents(fromDate, toDate))
            {
                eventsList.Add(new CalendarDTO
                    {
                        id = ev.ID,
                        title = ev.Title,
                        start = ToUnixTimespan(ev.Date.Value),
                        end = ToUnixTimespan(ev.EndDate.Value),
                        url = "www.huntsac.co.uk"
                    });
            }

            return Json(eventsList, JsonRequestBehavior.AllowGet);
        }

        private long ToUnixTimespan(DateTime date)
        {
            TimeSpan tspan = date.ToUniversalTime().Subtract(
         new DateTime(1970, 1, 1, 0, 0, 0));

            return (long)Math.Truncate(tspan.TotalSeconds);
        }


        private static DateTime ConvertFromUnixTimestamp(double timestamp)
        {
            var origin = new DateTime(1970, 1, 1, 0, 0, 0, 0);
            return origin.AddSeconds(timestamp);
        }
    }
    public class CalendarDTO
    {
        public int id { get; set; }
        public string title { get; set; }
        public long start { get; set; }
        public long end { get; set; }
        public string url { get; set; }
    }
}

HAC.Web/Views/Shared/Announcement1.cshtml
@model HAC.Domain.Announcement
@{
    ViewBag.Title = "AddAnnouncement";
}

@using (Html.BeginForm("Save", "Announcement"))
{
    <table border="0" width="82%">

        <tr>
            <td width="10%" align="right"><font face="Tahoma, Verdana, Arial, Helvetica, sans-serif" size="2">Title:</font></td>
            <td><font face="Tahoma, Verdana, Arial, Helvetica, sans-serif" size="2"> 
                    <input type="text" name="Title" size="80">
                </font><font face="Tahoma, Verdana, Arial, Helvetica, sans-serif" size="2">&nbsp; 
                       </font></td>
            <td rowspan="2">&nbsp;</td>
        </tr>

        <tr>
            <td width="10%" height="20" align="right"><font face="Tahoma, Verdana, Arial, Helvetica, sans-serif" size="2">Date:</font></td>
            <td colspan="2" height="20"><font face="Tahoma, Verdana, Arial, Helvetica, sans-serif" size="2">

                @Html.EditorFor(model => model.ExpiryDate)

            </td>
        </tr>

        <tr>
            <td width="10%" align="right" valign="top"><font face="Tahoma, Verdana, Arial, Helvetica, sans-serif" size="2">Description:</font></td>
            <td><font face="Tahoma, Verdana, Arial, Helvetica, sans-serif" size="2"> 
                    <textarea name="Description" wrap="VIRTUAL" cols="100" rows="20"></textarea>
                </font></td>
            <td align="right" valign="top">&nbsp;</td>
        </tr>

        <tr>
            <td align="right">&nbsp;</td>
            <td colspan="2"><font face="Tahoma, Verdana, Arial, Helvetica, sans-serif" size="2">&nbsp; 
                                <input type="submit" value="Add Event">
                            </font></td>
        </tr>
    </table>
}



HAC.Web/Views/Shared/CategoryTree.cshtml
@using System.Collections
@using HAC.Domain
@model List<pic_categories>

<ul> 
 @foreach (var cat in (ViewData.Model))
 {

     <li class="subfolder">
         <a rel="" href="@Url.Action("List", "Category", new { iCat = @cat.CAT_ID})">@cat.CAT_NAME <span class="items">(@cat.pic_images.Count)</span></a>                
    
     </li>

 }
</ul>

HAC.Web/Views/Shared/FolderTree.cshtml
@using System.Configuration
@model IEnumerable<PGFolder>

<ul> 
 @foreach (var subfolder in (ViewData.Model))
 {
    var showfolder = true;
    var showSubfolders = true;
     
    string className = "folder"; //default style
    if (subfolder.Security.PrivateFolder)
    {
        if (subfolder.IsUserGranted(User.Identity.Name))
        {
            className = "private";
        }
        else
        {
            if (Configuration.GetConfiguration().HidePrivateFolders) {
                showfolder = false;
            }
            else{
                showSubfolders = false;
                className = "denied";
            }            
        }
    }
    else
    {
        if (subfolder.SubFolders.Count == 0)
        {
            className = "subfolder";
        }
    }

    if (showfolder)
    {
    <li class="@className">
    <a rel="@subfolder.VPath" href="@Url.Action("List", "Folder", new { folder = HttpUtility.UrlEncode(subfolder.VPath) })">@subfolder.Name <span class="items">(@subfolder.FolderInfo)</span></a>                
    @if (showSubfolders && subfolder.SubFolders.Count > 0)
    {             
        <text>
        @{Html.RenderPartial("FolderTree", subfolder.SubFolders);}   
        </text>                                                        
    }
    </li>    
    }
 }
</ul>

HAC.Web/Views/Shared/LatestAnnouncements.cshtml
@using HAC.Domain
@using System
@model List<Announcement>
<dl class="news">

    @foreach (Announcement announcement in Model)
    {
       
        <dt>@announcement.Title</dt>
        <dd>@Html.Raw(announcement.Title)
        </dd>
    }
    @* <dt>St Ives 10k - 21st July 2013</dt>
    <dd><a href="#">Help required
                                                                        <img alt="" src="@Url.Content("~/Content/images/marker.gif")" /></a></dd>
    <dt>Serie A</dt>
    <dd><a href="#">Impossible to stop Inter praesent vestibulum molestie lacus.
                                                                        <img alt="" src="@Url.Content("~/Content/images/marker.gif")" /></a></dd>
    <dt>Serie A</dt>
    <dd class="last"><a href="#">Milan is saving the intrigue.
                                                                                     <img alt="" src="@Url.Content("~/Content/images/marker.gif")" /></a></dd>*@
</dl>

HAC.Web/Views/Shared/LatestEvents (Marshal's conflicted copy 2013-05-22).cshtml
@using HAC.Domain
@model List<Event>
<!-- title-box4 begin -->

<div class="title-box4">
    <div class="left">
        <div class="right">
            <div class="wrapper">
                <a href="#" class="link6 fright">All Events</a><h2>Next Events</h2>
            </div>
        </div>
    </div>
</div>
<!-- title-box4 end -->
<!-- box3 begin -->
<div class="box3">
    <div class="right-bot-corner">
        <div class="left-bot-corner">
            <div class="inner1">
                <script>
                    $(document).ready(function () {
                        $("#latestEvents a").click(function () {

                            var href = $(this).attr("href");

                            if (href) {
                                $(href).dialog({
                                    modal: true,
                                    minWidth: 400,
                                    buttons: {
                                        Ok: function () {
                                            $(this).dialog("close");
                                        }

                                    }
                                });
                            }
                        });
                    });

                </script>
                @foreach (Event ev in Model)
                {
                    <div id="@ev.ID" class="dialog" title="Upcoming Event" style="display:none">
                        <p id="title">@ev.Title  test</p>
                        <p id="wrapper">Location: @ev.Location</p>
                        <p>Date: @ev.Date</p>
                        <p>Description: @ev.Description</p>
                        <p>URL: <a target="_new" href="@ev.URL">@ev.URL</a></p>
                        <div id="postedby">Posted by @ev.name @ev.lname on @ev.udate</div>
                    </div>
   
                }
                <ul class="list1" id="latestEvents">

                    @foreach (Event ev in Model)
                    {
                        <li>
                            <div>
                                @ev.Date @Html.ActionLink("ICS", "ICal", "Events",  new { id = @ev.ID }, null)
                            </div>
                            <a href="#@ev.ID">@ev.Title</a></li>
                    }
                </ul>

            </div>

        </div>
    </div>
</div>
<!-- box3 end -->




HAC.Web/Views/Shared/LatestEvents.cshtml
@using HAC.Domain
@model List<Event>
<!-- title-box4 begin -->

<div class="title-box4">
    <div class="left">
        <div class="right">
            <div class="wrapper">
                <a href="#" class="link6 fright">All Events</a><h2>Next Events</h2>
            </div>
        </div>
    </div>
</div>
<!-- title-box4 end -->
<!-- box3 begin -->
<div class="box3">
    <div class="right-bot-corner">
        <div class="left-bot-corner">
            <div class="inner1">
                <script>
                    $(document).ready(function () {
                        $("#latestEvents a").click(function () {

                            var href = $(this).attr("href");

                            if (href) {
                                $(href).dialog({
                                    modal: true,
                                    minWidth: 400,
                                    buttons: {
                                        Ok: function () {
                                            $(this).dialog("close");
                                        }

                                    }
                                });
                            }
                        });
                    });

                </script>
                @foreach (Event ev in Model)
{
    <div id="@ev.ID" class="dialog" title="Upcoming Event" style="display:none">
        <p id="title">@ev.Title  test</p>
        <p id="wrapper">Location: @ev.Location</p>
        <p>Date: @ev.Date</p>
        <p>Description: @ev.Description</p>
        <p>URL: <a target="_new" href="@ev.URL">@ev.URL</a></p>
        <div id="postedby">Posted by @ev.name @ev.lname on @ev.udate</div>
    </div>
   
}
                <ul class="list1" id="latestEvents">

                    @foreach (Event ev in Model)
                    {
                        <li>
                            <div>
                                @ev.Date
                            </div>
                            <a href="#@ev.ID">@ev.Title</a></li>
                    }
                </ul>

            </div>

        </div>
    </div>
</div>
<!-- box3 end -->




HAC.Web/Views/Shared/NewsItems.cshtml
@using HAC.Domain
@model List<Event>
<!-- title-box1 begin -->
<div class="title-box1">
    <div class="left-top-corner">
        <div class="right-top-corner">
            <div class="right-bot-corner">
                <div class="left-bot-corner">
                    <div class="inner">
                        <div class="wrapper">
                            <a href="#" class="link3 fright">Archive</a><h3>Top news items</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- title-box1 end -->
<!-- box1 begin -->
<div class="box2">
    <div class="right-bot-corner">
        <div class="left-bot-corner">
            <div class="inner">

                @foreach (Event news in Model)
                {
                    <!-- events block begin -->
                    <div class="box3">
                        <div class="left-top-corner">
                            <div class="right-top-corner">
                                <div class="border-top"></div>
                            </div>
                        </div>
                        <div class="border-left">
                            <div class="border-right">
                                <div class="inner">
                                    <div class="extra-wrap">
                                        <img class="img-indent" alt="" src="@Url.Content("~/Content/images/run_icon.jpg")" />
                                        @Html.ActionLink(news.Title + " " + news.Date, "Details", "News", new { Id = news.ID }, new { @class = "h6Link" })
                                        @MvcHtmlString.Create(news.NewsShort) ....
                                                                            <div class="wrapper"><b>@Html.ActionLink("more info", "Details", "News", new { Id = news.ID }, new { @class = "link1" })</b></div>
                                    </div>
                                    <div class="clear"></div>
                                </div>
                            </div>
                        </div>
                        <div class="left-bot-corner">
                            <div class="right-bot-corner">
                                <div class="border-bot"></div>
                            </div>
                        </div>
                    </div>
                    <!-- events block end -->
                }
            </div>
        </div>
    </div>
</div>
<!-- box1 end -->

HAC.Web/Views/Shared/SignIn.cshtml
<script>
    $(document).ready(function () {
        $("#signin").click(function () {
            openDialog();
        });

        function openDialog() {
            $("#signindiv").dialog({
                modal: true,
                minWidth: 300,
                buttons: {
                    Submit: function () {
                        $("#signinform").submit();
                    }
                }
            });
        };


        if ($("#loginpage").length > 0) {
            openDialog();
        }


        $('#signinform').submit(function (event) {
            event.preventDefault();
            $('#errormessage').text(" ");
            $("*").removeClass("ui-state-error");
            var $form = $(this),
                username = $form.find('input[name="username"]').val(),
                password = $form.find('input[name="password"]').val(),
                url = $(this).attr('action');
            if (username == "") {
                $form.find('input[name="username"]').addClass("ui-state-error");
                $('#errormessage').text("Please enter a username");
                return;
            }
            if (password == "") {
                $form.find('input[name="password"]').addClass("ui-state-error");
                $('#errormessage').text("Please enter a password");
                return;
            }
            $("*").addClass("busy");
            $.post(url, { username: username, password: password }, function (response) {
                $("*").removeClass("busy");
                if (response.success) {
                    window.location.href = response.redirect;

                    return;
                }
                $('#errormessage').text(response.error);
            });

        });

    });

</script>

@if (HttpContext.Current.User.Identity.IsAuthenticated)
{
    <div class="signin">
        @Html.ActionLink("Sign Out", "SignOut", "Account")
    </div>
    
    
}
else
{
    <div class="signin"><a id="signin" href="#">Sign in</a></div>
}

<div id="signindiv" class="signin" title="Sign in with your HAC ID" style="display: none">
    <p class="validateTips" id="errormessage">All form fields are required.</p>
    <form method="post" id="signinform"
          action="@Url.Action("SignIn", "Account")">
        <fieldset>
            <label for="email">Email</label>
            <input type="text" name="username" id="username" value="" class="text ui-widget-content ui-corner-all" />
            <label for="password">Password</label>
            <input type="password" name="password" id="password" value="" class="text ui-widget-content ui-corner-all" />
            @*   <input type="submit" value="Sign in"/>*@
        </fieldset>
    </form>

</div>




HAC.Web/Views/Shared/UnderConstruction.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>UnderConstruction</title>
</head>
<body>
    <div>
         <img alt="Under Construction" src="@Url.Content("~/Content/images/UnderConstruction1.png")" />
    </div>
</body>
</html>